# Generated by Django 5.0 on 2024-03-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_first_name_alter_usermodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
