# Generated by Django 5.0 on 2024-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_date_joined_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.CharField(max_length=20, verbose_name='Mobile number'),
        ),
    ]
